name: Java CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: set build number
        run: echo "CURRENT_BUILD_NUMBER=$(echo $(git tag| head -1) + 1 | bc)" >> $GITHUB_ENV
      - name: Build with Ant
        run: |
          echo currentbuildnumber = ${{ CURRENT_BUILD_NUMBER }}
          ant -noinput -buildfile scripts/build.xml -DBUILD_NUMBER=${{ CURRENT_BUILD_NUMBER }} -Dbasedir=.
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: WebApp
          path: TestHello.war
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iv1infovista/testgwt:version1.0.001
