name: Java CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      - name: Build with Ant
        run: ant -noinput -buildfile scripts/build.xml -Dbasedir=.
      - uses: actions/upload-artifact@v2
        with:
          name: WebApp
          path: TestHello.war
      - name: Build docker
        run: docker build . -t iv1infovista/testgwt/version1.0
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: iv1infovista/testgwt
          tag_with_ref: true
